### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by brunoborges** [oracle/xml-sample-demo#1]
Is it possible to rename this repository to state this is an XML sample for Oracle DB? Suggestions:
- `oracle-db-xml-samples`
- `oracle-db-xml-demos`

**Comment by markddrake** [comment]
It would be difficult as it would break a lot of links and collateral

**Comment by brunoborges** [comment]
Renamed repositories continue to be accessible by the old name, giving enough time for external links to be updated.
